spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/paste?charset=utf8mb4&useSSL=false
    username:
    password:
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 50mb
      max-request-size: 50mb
server:
  port: 8087

